FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04 as base

WORKDIR /openkf-bot

ADD /bot .

FROM python:3.9 as builder

WORKDIR /openkf-bot

COPY --from=base /openkf-bot .

RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3  install -r requirements.txt
RUN chmod +x ./start.sh


EXPOSE 10011

ENTRYPOINT ["./start.sh"]